// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyyfywzhxcnffdjbxrxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55eWZ5d3poeGNuZmZkamJ4cnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzU0NTIsImV4cCI6MjA2Njc1MTQ1Mn0.slChuAniC5fpE2WPxr2oCknAn9F-0zWlYSQTq_DsghI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);